### ISSUE TITLE
structured relationship mining algorithms

### ISSUE THREAD

**Issue by simonzachau** [MusicConnectionMachine/RelationshipsG4#12]
Compared to unstructured relationship mining, where we need to analyse the given sources, all the data should already be stored. 
Our idea is to then compare the stored entities; e.g. 2 musicians living at the same time period results in a new relationship entry. This works for some of the [relationships, which we expect to be able to extract](https://github.com/MusicConnectionMachine/RelationshipsG4/blob/develop/documents/Relationships.txt).

**Comment by simonzachau** [comment]
It is suggested that we concentrate more on unstructured relationships because @MusicConnectionMachine/group-1 [might already store relationships of structured sources](https://github.com/MusicConnectionMachine/StructuredData/issues/8#issuecomment-284748581)?

**Comment by kordianbruck** [comment]
@simonzachau progress on this? Can this be closed?

**Comment by simonzachau** [comment]
@kordianbruck At least we are not focussing on this for now, as the unstructured ones are the real challenge and need our attention. In the beginning we opened this issue to differentiate between structured and unstructured mining, but the work turned into mining unstructured sources only.
