### ISSUE TITLE
Alternatives (for d3)

### ISSUE THREAD

**Issue by FelsyWaschbaer** [MusicConnectionMachine/RelationshipsG4#16]
- [ ] [Chart.js](http://www.chartjs.org)
- [ ] [Raphaël.js](http://dmitrybaranovskiy.github.io/raphael)
- [ ] [nvd3.js](http://nvd3.org)

**Comment by sacdallago** [comment]
https://github.com/MusicConnectionMachine/RelationshipsG4/issues/17#issuecomment-284823760
