### ISSUE TITLE
Prepare workshop

### ISSUE THREAD

**Issue by FelsyWaschbaer** [MusicConnectionMachine/RelationshipsG4#17]

**Comment by sacdallago** [comment]
I know this sounds suuuuper evil and stuff but... Could you move the discussion for all the items in the `presentation` label to a different place? Eventually you can also open up another repo (in this organisation or on someone's github) and discuss/throw your data around there (I've noticed you have opened a `presentation` branch in this repo).

To give you a couple of reasons why:
- Presentations are not relevant to the projects and it is bad practice to mix this-and-that.
- It is really hard to stay on top of all the issues, PRs and discussions for all the projects for us tutors. Adding new items to the stack doesn't help.
- These items (the presentation related issues) are things we tutors should be able to ignore (we **will not** correct your presentations until you actually present in late March), without ignoring the project-relevant issues.

Merci 👼  And sorry. Really 😢 But I hope you see the point!
