### ISSUE TITLE
filtering relationship extraction from json

### ISSUE THREAD

**Issue by simonzachau** [MusicConnectionMachine/RelationshipsG4#25]
For now we get the openIE results in the JSON format with coreferences inline. Next, we have to extract relevant information from the openIE triplets, e.g. ("Mozart", "born in", "Salzburg") -> search for the "born in"-relationship and save to the database via the api.

**Comment by simonzachau** [comment]
Update: In the meeting on Friday @vviro made clear that it's better to store much data than to filter it aggressively. Consequently, we might even be able to store the data directly without trying to understand any logic.

**Comment by Sandr0x00** [comment]
Just committed some changes:
We now automatically save data on the FS (configurable via config.json), since we not yet have db-logic in place.
branch at the moment: filtering

**Comment by kordianbruck** [comment]
@Sandr00 please make sure the DB-logic is there first then and work on that instead. Thanks!

We need to halt any other progress and get the basics done first!

**Comment by Sandr0x00** [comment]
@Gillian0023 works at the moment on the DB logic in the API. (https://github.com/MusicConnectionMachine/api/issues/28)

**Comment by kordianbruck** [comment]
@Sandr00 can you support her and fasttrack that issue please? Thanks!

**Comment by Sandr0x00** [comment]
Sure

**Comment by Sandr0x00** [comment]
Continued here: https://github.com/MusicConnectionMachine/Relationships/issues/9
