### ISSUE TITLE
Cloud data storage format

### ISSUE THREAD

**Issue by nbasargin** [MusicConnectionMachine/RelationshipsG4#38]
Please discuss cloud data data format here: https://github.com/MusicConnectionMachine/UnstructuredData/issues/68

**Comment by Sandr0x00** [comment]
Then, we close this one here, ok?

**Comment by simonzachau** [comment]
@nyxathid This is like a duplicate issue then. You can reference us in your issue and I am going to close this one as we don't see a purpose for it.
