### ISSUE TITLE
Setting up continuous integration

### ISSUE THREAD

**Issue by simonzachau** [MusicConnectionMachine/RelationshipsG4#40]
My current idea: Github --(1)--> Travis --(2)--> Docker --(3)--> Azure
1. Works.
2. What is the best way? Should we do it like [mentioned here](https://sebest.github.io/post/using-travis-ci-to-build-docker-images/)?
3. We are [experimenting on Azure](https://github.com/MusicConnectionMachine/RelationshipsG4/issues/34).

**Comment by kordianbruck** [comment]
Great, please implement this till the set milestone. 

Regarding 2/3: I think @sacdallago said its best to use [dockerhub](https://hub.docker.com/)

**Comment by kordianbruck** [comment]
Checkout (and copy?): https://github.com/MusicConnectionMachine/VisualizationG6/blob/develop/.travis.yml
https://github.com/MusicConnectionMachine/VisualizationG6/blob/develop/Dockerfile

**Comment by sacdallago** [comment]
You can still user Travis to run tests + docker (hub's automatic build) to run the build, then you basically two testing mechanisms.

For deployment, you can directly do docker hub -> Azure via the Linux App Service, it _should_ also directly fetch new builds from docker hub, but this I've never had time to test

**Comment by simonzachau** [comment]
@kordianbruck For step 2 (Travis->Docker) I followed the example of the .travis.yml file from @MusicConnectionMachine/group-6, however, Travis always tells me `Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password` even though the login on my local machine works fine.
@sacdallago For step 3 (Docker->Azure) I know that it works, we've tested that.

**Comment by kordianbruck** [comment]
Did you set $DOCKER_USERNAME and the password in the environment variables?

**Comment by simonzachau** [comment]
@kordianbruck yes

**Comment by simonzachau** [comment]
I even tried it with environment variables in the .travis.yml instead of the settings pane now. But it refuses to authorize.

**Comment by simonzachau** [comment]
Step 2 (Travis->Docker) is working now!
My Password contained spaces which needed to be escaped in the environment variables.
Thanks @Henni for taking a look at it together.

Step 3 (Docker->Azure) is already tested with another image. So the rest of the CI work will be done on #34 . Therefore, I'll close this issue now.

**Comment by kordianbruck** [comment]
Who has spaces in his password - really? :dagger:

**Comment by Sandr0x00** [comment]
Here! 😋

**Comment by simonzachau** [comment]
well... when your password is more of a passphrase then you do ;-)

**Comment by simonzachau** [comment]
Btw. the built docker is sent to `musicconnectionmachine/relationshipsg4` now.
