### ISSUE TITLE
Sample Data for Groups 5/6

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/RelationshipsG4#49]
Maybe I'm missing it, but I can't seem to find it.

You guys need to give them some sample data that they can work with. Thanks!

**Comment by Sandr0x00** [comment]
Dependencies: Data extraction from WET-Files (#44) and then rough filtering the output-JSON (#47, #25) to more or less useful stuff G5/6 can actually use

**Comment by kordianbruck** [comment]
@Sandr00 so basically you are telling me, that since the first deadline on 17.03, where we already asked you guys to provide sample data to the other teams, you have not accomplished it till now?

**Comment by Sandr0x00** [comment]
We have accomplished it. But with our own data. Not yet with the data from the WET-files, we got recently.
Should I upload it here?
Also, the data is mostly junk and we will do more filtering, but therefore we need more data to filter out "good" data, which occurs more times, and "bad" data, which occurs only in one source.
But exactly that depends on the WET-Files.

**Comment by kordianbruck** [comment]
Sure, here is as good as anywhere. 

Give us a first revision, so we can actually see where we are at and the other teams can start thinking about how to use it.

**Comment by Sandr0x00** [comment]
Filtered to a certain degree: [openIE.zip](https://github.com/MusicConnectionMachine/RelationshipsG4/files/875805/openIE.zip)
Unfiltered: [rawDataFromNLP.zip](https://github.com/MusicConnectionMachine/RelationshipsG4/files/875823/rawDataFromNLP.zip)

**Comment by kordianbruck** [comment]
@MusicConnectionMachine/group-5 @MusicConnectionMachine/group-6 can you take a look at this data please?

**Comment by FelsyWaschbaer** [comment]
I think this is done.
