### ISSUE TITLE
Setup Default Project with Webstorm

### ISSUE THREAD

**Issue by Sandr0x00** [MusicConnectionMachine/RelationshipsG4#5]
Someone should set up a project and commit it here, so we all can start from the same source.

**Comment by sacdallago** [comment]
A pointer:
> Someone

**is no one!** 😆 

Next time, assign **someone** here on the right -->
and that **someone** might even be you 🙈 

IF the assigned person will have to much to do or is in a bad mood, they may reassign and discuss, nevertheless we don't generate the someone == no one problem (trust me, it happens more often than I'd like!)
