### ISSUE TITLE
Implement Database Adapter

### ISSUE THREAD

**Issue by Sandr0x00** [MusicConnectionMachine/RelationshipsG4#6]
Depending on data from Group 1/2, we have to create a adapter, which handles the DB-interaction.
Get data from DB.
Save data to DB.
Make data it usable for our logic parts.

Reason: If the DB changes we do not have to change every logic-part, but only the adapter.

**Comment by simonzachau** [comment]
Closing this issue as we want to implement [one API](MusicConnectionMachine/api) for all groups.
