### ISSUE TITLE
Topic Presentation

### ISSUE THREAD

**Issue by Sandr0x00** [MusicConnectionMachine/RelationshipsG4#7]
Our topic is: https://rostlab.org/owiki/index.php/Javascript_technology_2017#Theme_3
We have to present D3: https://d3js.org/

**Comment by Sandr0x00** [comment]
Info from Guy:
For starters, we will get you to read about the theme you chose to cover and then talk to your teammates about what you read. You and your team will then have to come up with a (roughly) **45 minutes** long talk that is about your topic and project, and that you (and your teammates) will present to the rest of us during presentation week March 22 -March 24. We're sure you'll do an amazing job!  
_He changed everything ...._

**Comment by simonzachau** [comment]
Project specific assignment information: 
"Title: Data Driven Documents: Data visualization using D3.js
Description: [...] We’ll first take a look at what Data Driven Documents are, why and how to use them. This is a very visual topic, so apart from the concept, there will be a focus on the look & feel of D3. Also present a few alternatives that are better or worse than D3 to see what to use in your own projects in the future."

**Comment by Sandr0x00** [comment]
**Info from Guy: Time**
**Theme / Topic presentation** [40min (30min presentation, 10min Q&A)]
Introduce the theory behind the theme.

**Interactive workshop on theme / topic** [40min]
Show how we implemented the theme in practice. After the workshop everyone should be able to use your presented technology in their respective projects.

**Project roundup** [minimum 10min]
Present the project you implemented and talk about problems we’ve encountered as well as lessons we take away.


**Deadline for Slides moved:**
We want you to plan out this time slot as much as possible and show your creativity in teaching us the techniques you’ve learned. For the workshop you can chose to let everyone code, live-code yourself or simply hand out a ready to run project that you will explain. Please send us your presentation slides and planned schedule for your slot till tuesday, 21.03.2017 @23:56.

**Comment by Sandr0x00** [comment]
Cool Stuff you can do with D3:
https://github.com/d3/d3/wiki/Gallery

A presentation from the mentors about D3:
https://drive.google.com/file/d/0B4mUQo6_fgAWVmUtLXc0VTZXejg/view

Alternatives to D3 (Summary):
https://www.slant.co/options/10577/alternatives/~d3-js-alternatives
http://alternativeto.net/software/d3-js/
http://chimera.labs.oreilly.com/books/1230000000345/ch02.html#_tools_built_with_d3

Alternatives to D3:
http://raphaeljs.com/
http://www.chartjs.org/

Of course the Wikipedia link:
https://en.wikipedia.org/wiki/D3.js

**Comment by simonzachau** [comment]
Work on this matter will take place in the [presentation branch](https://github.com/MusicConnectionMachine/RelationshipsG4/tree/presentation/presentation).

**Comment by sacdallago** [comment]
Goes with https://github.com/MusicConnectionMachine/RelationshipsG4/issues/17#issuecomment-284823760

@simonzachau presentation branch not good practice 🙈
